# This is the security configuration file for the application.
# It defines the security settings and access control rules.

security:
  enabled: true # Enables or disables the security system. Set to true to enable security.

  access_control:
    # Access control rules define which roles have access to specific paths.
    # Each rule consists of a path pattern and the roles that are allowed to access it.

    # Example:
    # - { path: ^/admin, roles: ROLE_ADMIN }  # Only users with ROLE_ADMIN can access paths starting with /admin
    # - { path: ^/profile, roles: ROLE_USER }  # Only users with ROLE_USER can access paths starting with /profile

    - { path: ^/users, roles: ROLE_USER }
    - { path: ^/products, roles: ROLE_ADMIN }
    - { path: ^/vue, roles: ROLE_USER }
