name: Deploy Docs to GitHub Pages

on:
  # Déclenchement sur push vers main
  push:
    branches: [ main ]
    paths: 
      - 'docs/framefox/**'  # Seulement si des fichiers docs changent
  
  # Permet le déclenchement manuel
  workflow_dispatch:

# Définit les permissions nécessaires
permissions:
  contents: read
  pages: write
  id-token: write

# Empêche les déploiements concurrents
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'docs/framefox/package-lock.json'
          
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
        
      - name: Install dependencies
        run: |
          cd docs/framefox
          npm ci
          
      - name: Build with Astro
        run: |
          cd docs/framefox
          npm run build
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/framefox/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4